export const APPLICATION_CATALOG = [
  {
    id: "single-beam-design",
    name: "Single Beam Design",
    domain: "beams",
    maturity: "mvp",
    primaryFocus: "End-to-end simple beam analysis, verification and reporting.",
  },
  {
    id: "steel-frames",
    name: "Steel Frames",
    domain: "steel",
    maturity: "scaffolded",
    primaryFocus: "Analysis and checks of steel frames and members.",
  },
  {
    id: "masonry-ring-beams",
    name: "Masonry Ring Beams",
    domain: "masonry",
    maturity: "scaffolded",
    primaryFocus: "Sizing and verification of cerchiature in masonry walls.",
  },
  {
    id: "reinforced-concrete-sections",
    name: "RC Sections",
    domain: "reinforced-concrete",
    maturity: "scaffolded",
    primaryFocus: "Section analysis for axial force and bending.",
  },
  {
    id: "timber-beams",
    name: "Timber Beams",
    domain: "timber",
    maturity: "scaffolded",
    primaryFocus: "Verification of timber beams in resistance and serviceability.",
  },
  {
    id: "timber-concrete-composite-beams",
    name: "Timber Concrete Composite Beams",
    domain: "timber",
    maturity: "implemented",
    primaryFocus: "Verification of timber beams with collaborating concrete slab.",
  },
  {
    id: "timber-xlam-composite-beams",
    name: "Timber XLAM Composite Beams",
    domain: "timber",
    maturity: "implemented",
    primaryFocus: "Verification of timber beams collaborating with XLAM panels.",
  },
  {
    id: "xlam-panels-out-of-plane",
    name: "XLAM Panels Out Of Plane",
    domain: "timber",
    maturity: "implemented",
    primaryFocus: "Out-of-plane verification of standalone XLAM floor panels.",
  },
  {
    id: "rc-cracked-deflection",
    name: "RC Cracked Deflection",
    domain: "reinforced-concrete",
    maturity: "scaffolded",
    primaryFocus: "Deflection analysis of cracked RC beams.",
  },
  {
    id: "masonry-out-of-plane",
    name: "Masonry Out Of Plane",
    domain: "masonry",
    maturity: "scaffolded",
    primaryFocus: "Local out-of-plane kinematic mechanisms in masonry walls.",
  },
  {
    id: "micropiles-broms",
    name: "Micropiles Broms",
    domain: "geotechnics",
    maturity: "scaffolded",
    primaryFocus: "Micropile lateral analysis based on Broms theory.",
  },
];
