import {
  NTC2018_ACTION_COMBINATION_FACTORS,
  NTC2018_ACTION_PARTIAL_FACTORS,
} from "../actions/ntc2018ActionParameters.js";

export const NTC2018_VARIABLE_ACTION_CATEGORIES = NTC2018_ACTION_COMBINATION_FACTORS;

export const NTC2018_ULS_PARTIAL_FACTORS = {
  G1_UNFAVOURABLE: NTC2018_ACTION_PARTIAL_FACTORS.permanent.G1.A1.unfavourable,
  G1_FAVOURABLE: NTC2018_ACTION_PARTIAL_FACTORS.permanent.G1.A1.favourable,
  G2_UNFAVOURABLE: NTC2018_ACTION_PARTIAL_FACTORS.permanent.G2.A1.unfavourable,
  G2_FAVOURABLE: NTC2018_ACTION_PARTIAL_FACTORS.permanent.G2.A1.favourable,
  Q_UNFAVOURABLE: NTC2018_ACTION_PARTIAL_FACTORS.variable.imposed.A1.unfavourable,
  Q_FAVOURABLE: NTC2018_ACTION_PARTIAL_FACTORS.variable.imposed.A1.favourable,
};
